### ISSUE TITLE
Cannot read property 'addTemplate' of undefined

### ISSUE THREAD

**Issue by Burtonium** [ivodolenc/nuxt-font-loader#3] opened 2021-02-17 19:30 UTC
As soon as I try to add any url this package fails.

Here's the stack trace:

Cannot read property 'addTemplate' of undefined                                  02:28:01

  at addPlugin (node_modules/@nuxt/core/dist/core.js:83:26)
  at ModuleContainer.fontLoader (node_modules/nuxt-font-loader/src/index.js:246:5)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:215:34)
  at node_modules/@nuxt/utils/dist/utils.js:1803:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:39:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:685:5)

**Comment by ivodolenc** [comment] 2021-02-17 20:53
Hi, thanks for using `nuxt-font-loader`. I just tested it with the latest `nuxt` version `2.15.0` and module works as expected.

I tried with `local` and `google` fonts (default and multiple source usage), can't reproduce your issue.

Test env:

- create-nuxt-app
- nuxt `2.15.0`
- nuxt-font-loader `1.1.3`

**Comment by Burtonium** [comment] 2021-02-18 14:55
I tried updating nuxt and it fixed the issue. You can close this ticket thank you for your time.

**Comment by ivodolenc** [comment] 2021-02-18 17:39
No problem, glad to help 👍 Closing this as resolved.

**Closed by ivodolenc** 2021-02-18 17:39 UTC
