### ISSUE TITLE
Eliminate render-blocking resources

### ISSUE THREAD

**Issue by nicoagp** [ivodolenc/nuxt-font-loader#28] opened 2024-05-14 05:24 UTC
### Steps to Reproduce

1. Install plugin
2. Load external typekit or google fonts 

### Current Behavior

I'm loading fonts from typekit:

```
  fontLoader: {
    external: [
      {
        src: 'https://use.typekit.net/upoxxx.css',
      },
    ]
  },
```
I see on the front end the font is being load at the very top of the head

< link rel="preconnect" crossorigin="anonymous" href="https://use.typekit.net" 

Is there any option to improve this to be able to avoid "Eliminate render-blocking resources" from Lighthouse ?
I'm getting this at the moment, sometimes less.
`
Potential savings of 1,770 ms
`

Fonts are already set to use font-display: swap 

Thank you

### Expected Behavior

To load the font and avoid render blocking resources

### Version

1

**Comment by ivodolenc** [comment] 2024-05-14 06:49
Hi, can you share more details or even better a minimal code reproduction (github repo link)?

How many font styles and weights do you use on the website? Is the font css file large?

Have you optimized the font from Typekit to explicitly use the language without additional versions if they are not needed? Can you use variable font and try again?

My opinion and advice is that of course if you can, use a local font. You manage privacy and save additional links to third-party servers. If you cannot use a local font, optimize the external font as much as possible before using it.

**Comment by nicoagp** [comment] 2024-05-14 07:29
Thank you for your reply.

I have created a minimal reproduction: https://stackblitz.com/edit/nuxt-starter-8fdxdx?file=nuxt.config.ts

_How many font styles and weights do you use on the website? Is the font css file large?_
2 Fonts, single weight each, I use only one weight, the css is 1b

_Have you optimized the font from Typekit to explicitly use the language without additional versions if they are not needed? Can you use variable font and try again?_
yes, I make them to use font-display: swap and remove "open type features" as I dont think I need them

I would love to you local fonts but the fonts I was given are in Adobe (which does not give you files

In my minimal repro I see it is adding a preconnect and preload but in my local project it is not adding preload, is there any reason of this? is it a way to force or add manually a preload?

**Comment by ivodolenc** [comment] 2024-05-14 08:24
Your project works fine as expected on my side.

![Screenshot 2024-05-14 at 10 14 51](https://github.com/ivodolenc/nuxt-font-loader/assets/51852491/161b9315-f52d-4ad5-82a1-c7ae72358fd3)


But as I mentioned, it preconnects and preloads css main font file which then loads other font files from typekit servers.

Try to download them, they are more than 50kb so they need some time. 

![Screenshot 2024-05-14 at 10 15 36](https://github.com/ivodolenc/nuxt-font-loader/assets/51852491/300d8db7-32c9-4851-8389-7c111cf0f50c)

But hey don't bother too much about lightscore, try to optimize all assets to the maximum and later on you will solve details like this. Also, try to manual load fonts and see difference, if module not for you use case, stick to your custom solution.

Since this works as expected, I'm closing this as resolved. Feel free to reopen if you still have issues.

**Closed as completed by ivodolenc** 2024-05-14 08:24 UTC
